export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST';
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS';
export const ITEM_LIST_FAILURE = 'ITEM_LIST_FAILURE';

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';
export const ITEM_DETAILS_FAILURE = 'ITEM_DETAILS_FAILURE';

export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
export const ITEM_CREATE_FAILURE = 'ITEM_CREATE_FAILURE';
export const ITEM_CREATE_RESET = 'ITEM_CREATE_RESET';

export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAILURE = 'ITEM_UPDATE_FAILURE';
export const ITEM_UPDATE_RESET = 'ITEM_UPDATE_RESET';